---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  dependsOn:
  - name: cert-manager-crds
  - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: homes
  path: ./deploy/cert-manager
  interval: 10m0s
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
spec:
  sourceRef:
    kind: GitRepository
    name: homes
  path: ./deploy/cert-manager/crds
  prune: false
  interval: 10m0s
  patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          kustomize.toolkit.fluxcd.io/prune: disabled
