apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  dependsOn:
  - name: monitoring-crds
  # - name: gateway-crds  # FIXME
  sourceRef:
    kind: GitRepository
    name: omes
  path: ./deploy/external-dns
  prune: true
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
