# https://fluxcd.io/flux/guides/webhook-receivers/

---
apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: flux-system
spec:
  type: LoadBalancer
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9292

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
spec:
  rules:
  - host: flux-webhook.webwur.st
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webhook-receiver
            port:
              number: 80


#         tolerations:
#         - effect: NoSchedule
#           key: dedicated
#           operator: Equal
#           value: gateway

# kubectl taint nodes talos-lea-lql dedicated=gateway:NoSchedule

#   "taints": [
#     {
#       "effect": "NoSchedule",
#       "key": "dedicated",
#       "value": "gateway"
#     }
#   ]
