---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: github-homes
spec:
  interval: 15m0s
  ref:
    branch: main
  url: https://github.com/webwurst/homes.git

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: homes
spec:
  type: oci
  url: oci://ghcr.io/webwurst/homes
