apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  dependsOn:
  - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: homes
  path: ./deploy/ingress-nginx
  prune: true
  interval: 1h
  decryption:
    provider: sops
    secretRef:
      name: sops-age
