apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# FIXME check `crds` field instead?
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/crds/
# configurations:
# - ../kustomizeconfig.yaml

crds:
- ./crds/receivers.notification.toolkit.fluxcd.io.yaml

namespace: flux-system
resources:
# - ./flux-components.yaml
- ./flux-components-minus-crds.yaml
- ./github-repo.yaml
- ./sync/flux-system.yaml
- ./sync/monitoring.yaml
- ./sync/ingress-nginx.yaml
- ./sync/external-dns.yaml
- ./sync/cert-manager.yaml
- ./sync/openebs.yaml
- ./sync/local-path-storage.yaml
# - ./sync/nextcloud-aio.yaml
- ./sync/nextcloud.yaml

secretGenerator:
- name: github-webhook
  files:
  - token=./github-webhook-secret
