nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    path: spec/valuesFrom/name
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    path: spec/valuesFrom/name
- kind: Secret
  version: v1
  fieldSpecs:
  - group: notification.toolkit.fluxcd.io
    version: v1
    kind: Receiver
    path: spec/secretRef/name
