apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ../kustomizeconfig.yaml

namespace: flux-system
resources:
- ./flux-components.yaml
- ./github-repo.yaml
- ./sync/flux-system.yaml
- ./sync/monitoring.yaml
- ./sync/ingress-nginx.yaml
- ./sync/external-dns.yaml
- ./sync/cert-manager.yaml
- ./sync/openebs.yaml
- ./sync/local-path-storage.yaml
# - ./sync/nextcloud-aio.yaml
- ./sync/nextcloud.yaml

secretGenerator:
- name: github-webhook
  files:
  - token=./github-webhook-secret
