apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system
resources:
- ./components
- ./ui
- ./cert-manager.yaml
- ./dex.yaml
- ./external-dns.yaml
- ./flux-system.yaml
- ./ingress-nginx.yaml
- ./local-path-storage.yaml
- ./monitoring.yaml
- ./nextcloud.yaml
- ./openebs.yaml
# - ./libre-booking.yaml
- ./velero.yaml
- ./nfs-ganesha.yaml
- ./erpnext.yaml
- ./respa.yaml
