apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ./kustomizeconfig.yaml

namespace: flux-system
resources:
- ./components
- ./cert-manager.yaml
- ./external-dns.yaml
- ./flux-system.yaml
- ./ingress-nginx.yaml
- ./local-path-storage.yaml
- ./monitoring.yaml
- ./nextcloud.yaml
- ./openebs.yaml

secretGenerator:
- name: flux-webhook
  files:
  - token=./flux-webhook-secret
