apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system
resources:
- ./flux-components.yaml
- ./github-homes.yaml
- ./sync/flux-system.yaml
- ./sync/monitoring.yaml
- ./sync/ingress-nginx.yaml
- ./sync/external-dns.yaml
- ./sync/cert-manager.yaml
- ./sync/openebs.yaml
- ./sync/local-path-storage.yaml
# - ./sync/nextcloud-aio.yaml
- ./sync/nextcloud.yaml
