# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: monitoring
# spec:
#   dependsOn:
#   - name: monitoring-crds
#   interval: 1h
#   path: ./deploy/monitoring
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-crds
spec:
  sourceRef:
    kind: GitRepository
    name: github-homes
  path: ./deploy/monitoring/crds
  prune: true
  interval: 1h
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          kustomize.toolkit.fluxcd.io/prune: disabled
