apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-ganesha
spec:
  sourceRef:
    kind: GitRepository
    name: homes
  path: ./deploy/infra/nfs-ganesha
  prune: true
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
