apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: respa
spec:
  # dependsOn:
  # - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: homes
  path: ./deploy/pgbuchung/respa
  prune: true
  interval: 10m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
