apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# configurations:
# - ../kustomizeconfig.yaml

namespace: dex
resources:
- manifests.yaml
- helm.yaml

secretGenerator:
- name: client-secrets
  files:
  - bitbucket-client-secret
  - grafana-client-secret
  - flux-dashboard-client-secret
  options:
    disableNameSuffixHash: true
