---
apiVersion: v1
kind: Namespace
metadata:
  name: dex

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dex
spec:
  interval: 1h0m
  url: https://charts.dexidp.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex
spec:
  secretName: dex-cert
  dnsNames:
  - dex.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
