gateway:
    basicAuth:
        password: ENC[AES256_GCM,data:6dQ3Nb/5wKS3A4oT5YvHRy7Cl/tQUyAKV4LNT8gb7CfeXmOtYj0iAw==,iv:f71sfrGcgMOdzVMDNfbUqdP30qpsxLbS7ItkSCg9eIU=,tag:gBt6i4ZKc5cGQW4U9jKXCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cw2ap3s3ufwreunvql5xpk56hf77hdkp4y586fcghpxeq27nw9zq0mse9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOVJDYjFOOFV4OFFrc1lL
            RmpkRlRISFdlOUZNUnlmZjdVcm9uQldHWW5nCmtRSEdDZHg4L0tKYWZsSUt2SC9U
            eGM0Y1Y5ZVNITHkzUEtGUS9ZQUZHcXcKLS0tIEQ1OXkyeFVFRVl6NFlCelZPWGta
            M2Fuc21pUnhOQ01Da0tpV2JsQjQ1QTQKFub0mLHAodky9P/ZwEVrPvxQg5ibpLQK
            b/JVNj5WQI3d4lT2exoSEI0lEGDqtAhoVnKzZZOWAlQuzjqSZYK05g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T01:11:14Z"
    mac: ENC[AES256_GCM,data:XMN1WiPaedn8OaLrL27DoWUCheDum/cEere1XhnCuc0gd4Ewl+W+NIRKsTt3HQ5TuinHo4iEc+owpfbM9CzIlez4S+4kqz8D1Sm13iKrTS+WGv/fA5y4iJXF33yDiu95mvv7t63EjNQpRftdSjjawanGfQTdfdTgRWqDLT/7+KQ=,iv:F8sf584yP/pU2iodzGjQvesQrT7Db6NnxDDgeOtRDAo=,tag:oRRxg0BuBVYHjf4ZhFlo8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
