apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./manifests.yaml
- ./helm.yaml
# - ./grafana-datasource-loki.yaml

secretGenerator:
- name: loki-helm-secrets
  files:
  - values.yaml=./helm-secrets.yaml
