apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki
spec:
  secretName: loki-cert
  dnsNames:
  - loki.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
