apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      # https://artifacthub.io/packages/helm/external-dns/external-dns
      version: "~1.14.1-patch1"
      sourceRef:
        kind: HelmRepository
        # name: external-dns
        namespace: flux-system
        name: homes
  storageNamespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  # postRenderers:
  # - kustomize:
  #     images:
  values:
    # default values: https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml

    # FIXME create non-root user in Dockerfile upstream
    #   https://github.com/mrueg/external-dns-netcup-webhook
    podSecurityContext:
      runAsNonRoot: false

    serviceMonitor:
      enabled: true

    interval: 10m
    # triggerLoopOnEvent: true
    triggerLoopOnEvent: false

    # https://github.com/kubernetes-sigs/external-dns/blob/master/docs/sources/sources.md
    sources:
    - ingress
    # - gateway-httproute
    # - gateway-tcproute
    # - gateway-tlsroute
    # - gateway-grcproute
    # - gateway-udproute

    txtOwnerId: homes
    domainFilters: ["webwur.st"]
    extraArgs:
    - --exclude-target-net=192.168.0.0/16

    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mrueg/external-dns-netcup-webhook
          tag: 0.0.7
        # FIXME remove "-" on upstream chart
        # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/templates/deployment.yaml#L147
        args:
        - --log-level=debug
        # # seems to be required
        - --domain-filter=webwur.st
        # https://github.com/mrueg/external-dns-netcup-webhook/blob/main/main.go#L23-L33
        env:
        - name: NETCUP_CUSTOMER_ID
          valueFrom:
            secretKeyRef:
              name: netcup-api
              key: customer-id
        - name: NETCUP_API_KEY
          valueFrom:
            secretKeyRef:
              name: netcup-api
              key: api-key
        - name: NETCUP_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: netcup-api
              key: api-password
        serviceMonitor: {}
          # FIXME add `enabled` upstream

  # postRenderers:
  # - kustomize:
  #     patches:
  #     - patch: |-
  #         apiVersion: apps/v1
  #         kind: Deployment
  #         metadata:
  #           name: external-dns
  #           namespace: external-dns
  #         spec:
  #           template:
  #             spec:
  #               containers:
  #               - name: webhook
  #                 args:
  #                 - --domain-filter=webwur.st
  #                 - --log-level=debug
