apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns
resources:
- manifests.yaml
- helm.yaml

# FIXME does not work with helm?
images:
- name: registry.k8s.io/external-dns/external-dns
  newTag: v0.14.0
  digest: sha256:474077b3dfccb3021db0a6638274967d0f64ce60dd9730a6f464bee2f78b046f
- name: ghcr.io/mrueg/external-dns-netcup-webhook
  newTag: 0.0.6
  digest: sha256:22b0f8133d6f2abd6b5cb0625b443f33e85b5fec64da8306be49f224133d2ce8

secretGenerator:
- name: netcup-api
  files:
  - customer-id=./netcup-api/customer-id
  - api-key=./netcup-api/api-key
  - api-password=./netcup-api/api-password
  # FIXME add kustomize reference instead
  options:
    disableNameSuffixHash: true
