---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
spec:
  url: https://kubernetes-sigs.github.io/external-dns/
  interval: 1h
