---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: zfs-localpv
spec:
  interval: 1h
  url: https://openebs.github.io/zfs-localpv
