---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    # FIXME Error creating: pods "zfs-localpv-node-wvfrd" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostNetwork=true), hostPath volumes (volumes "device-dir", "encr-keys", "host-root", "registration-dir", "plugin-dir", "pods-mount-dir"), privileged (container "openebs-zfs-plugin" must not set securityContext.privileged=true)
    # https://kubernetes.io/docs/concepts/security/pod-security-admission/#exemptions
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: zfs-localpv
spec:
  interval: 1h
  url: https://openebs.github.io/zfs-localpv

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs
allowVolumeExpansion: true
provisioner: zfs.csi.openebs.io
parameters:
  poolname: mpool
  fstype: zfs
