apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  dependsOn:
  - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: github-homes
  path: ./deploy/external-dns
  prune: true
  interval: 1h
  decryption:
    provider: sops
    secretRef:
      name: sops-age
