apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: github-homes
  path: ./deploy/flux-system
  prune: true
  interval: 1h
  decryption:
    provider: sops
    secretRef:
      name: sops-age
