apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
spec:
  # dependsOn:
  # - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: github-homes
  path: ./deploy/openebs
  prune: true
  interval: 1h
  decryption:
    provider: sops
    secretRef:
      name: sops-age
