apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: respa
resources:
- ./namespace.yaml
- ./respa.yaml
- ./postgis.yaml

secretGenerator:
- name: respa
  files:
  - ./secrets/secret-key
  - ./secrets/postgres-password
  options:
    disableNameSuffixHash: true
