---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varaamo
  labels:
    app: varaamo
spec:
  selector:
    matchLabels:
      app: varaamo
  template:
    metadata:
      labels:
        app: varaamo
    spec:
      containers:
      - name: varaamo
        image: docker.io/webwurst/varaamo:tku-v1.9
        # see https://github.com/City-of-Turku/varaamo/blob/develop/config/webpack.production.js#L57
        # (compare to https://github.com/City-of-Helsinki/varaamo/blob/master/config/settings.js#L42)
        env:
        - name: NODE_ENV
          value: production
        - name: CLIENT_ID
          value: ""
        # https://github.com/City-of-Helsinki/varaamo/blob/master/server/auth/configurePassport.js#L11
        # https://www.npmjs.com/package/redux-oidc
        # https://github.com/maxmantz/redux-oidc-example/blob/master/src/utils/userManager.js
        # https://github.com/maxmantz/redux-oidc-example/blob/master/src/utils/api.js#L25
        # - name: CLIENT_SECRET  # missing ?!
        #   value: ""
        - name: OPENID_AUDIENCE
          value: ""
        - name: OPENID_AUTHORITY
          value: ""
        - name: API_URL
          value: https://respa.webwur.st/v1/
        - name: ADMIN_URL
          value: https://respa.webwur.st/ra/
        # - name: THEME_PKG
        #   value: ""
        - name: APP_TIMEZONE
          value: Europe/Berlin
        - name: BLOCK_SEARCH_ENGINE_INDEXING
          value: "1"
        # - name: SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: varaamo
        #       key: secret-key
        ports:
        - name: http
          containerPort: 8080
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: varaamo
spec:
  ports:
  - name: http
    appProtocol: http
    port: 8080
  selector:
    app: varaamo

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: varaamo
spec:
  ingressClassName: nginx
  rules:
  - host: varaamo.webwur.st
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varaamo
            port:
              name: http
  tls:
  - hosts:
    - varaamo.webwur.st
    secretName: varaamo-cert

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: varaamo
spec:
  secretName: varaamo-cert
  dnsNames:
  - varaamo.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
