apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 1h0m
  chart:
    spec:
      chart: nextcloud
      # https://artifacthub.io/packages/helm/nextcloud/nextcloud
      version: "~4.5.11"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  storageNamespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip

  valuesFrom:
  - kind: Secret
    name: nextcloud-helm-secrets

  values:
    # for defaults see https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml

    ingress:
      enabled: true
      className: nginx
      tls:
      - secretName: nextcloud-cert
        hosts:
        - nextcloud.webwur.st
  
    nextcloud:
      host: nextcloud.webwur.st
      # for `password` see ./helm-secrets.yaml
