nextcloud:
    password: ENC[AES256_GCM,data:95HY5fZbl198sA5T0oJHjr3F0BsIuKVmio9lXUhy/tcVE5CeZA2qiA==,iv:4xK2RSlWpbgr8o/+yVMe3Leq/V/6Td2SFoR/UnYupAM=,tag:2KoAjkVEVyCiolaYMrTkdA==,type:str]
postgresql:
    global:
        postgresql:
            auth:
                password: ENC[AES256_GCM,data:hS88VdUTBNLAC/1KOdW6znwSYPSLbhQxJZ0GkdHKaPMOXQwPLyOcDA==,iv:oMiFLBpt7nmy8ZzUNuyeWSp0nQ6Af70F7KvATOkNwNk=,tag:tuXeNebYeVF4LwldlYsFUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cw2ap3s3ufwreunvql5xpk56hf77hdkp4y586fcghpxeq27nw9zq0mse9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVTZaeVJLTVBMQUZFT3FT
            dVM4V090c3FBYldXTVBqaFQzTForQlNoam5jCnVha2tFMDR5Y3RhNEJxc0IyODJl
            ZkhBQWZuSGFnQ0JHd2NxamFDV2NhL2cKLS0tIHZtMzJRa0NWdVdMellnOG9WbExB
            QnNhVmNLdFhmUi9HMjBNYlV5Z3JUMkkKrmRxyD7gYi6Tq/gXs1B1r6hc9bMFCpVb
            zzQD9r/oeTe835TFE3+1BWsQKh88P70R47ujZk61Vv+8MqTLzwDKdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T22:17:05Z"
    mac: ENC[AES256_GCM,data:9rC5Oze/POrOseAFXeXHwuj1nNvK0vjZidw0YH3q+iqifbX2uG0IOxvN9qd6fc5PnkeAMGsifQuKS4Ki+jnR1zESSqY3zy7Lt8i60JQoeSxEWN9U6Ybwi3gv/xkk0TMWiDek6bQL07tsdz7ZnO1Yi4+/84SkRE6xDN8EHW4+PPU=,iv:fgu6pAfbK3KTgxlEjmVSic1qjPp+SfyOOZ3HCJ9f2Cs=,tag:S0ofeJqTDtJtAvFiaDv3JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
