nextcloud:
    password: ENC[AES256_GCM,data:cnAPaY5DsvMsx/HNHlw0Jm801q/pJ36xbxJ6mGk3sAD9Y9WL8rQauA==,iv:dHbFE2Sj8nlfCSzEuzKXdvIMoj+pqu/qkGEEmxxv20k=,tag:ZImy64iNK4zf1q5gdn5LDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10pzhgqq3dyj080z597gctwr98dsjtca359l6ka08jwc46dztjupqzln5p7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWnBxNHZZNmFPSlJHb0do
            OVlIOWFWWXl5a0F1VTdCYTVCTGtIRWhlU2xZCk5tQ2dQSGlKMkhoOCtsTytSQkpI
            UXFSYVpRM0dOUFpXd0RjNzF3MFNXcjgKLS0tIGZBOFJMS2E5WVdYSFg0VWQvcnBN
            VlBEaTBRVnJ6WTVlUWZvV2NnWUtWa0kKsG/afWk4/h85tUJnN4wO7f39AlCCrvfs
            D02PlIypPG5OzMwXnfq5mnx9xkkZPTQejWUx+ObOpPQRW5Wdb2sARg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T21:33:46Z"
    mac: ENC[AES256_GCM,data:tFfgAiPLX2P345OHRK0/Ax0c5TOWIrmt/CHdt/lDmIOQXGqiNAmtOHTdzOpXuwrMwB96Q6a1WjuKOwDlSBhpafa/oYYr9C+3Q4gujExts93xgIT2aQoeUtQhGGNB5CPYSZm8SGiB0SQT7P2it8HZa070iFT52YEtht8na1Q+jpE=,iv:6q5reL8NECBlVq0R4T+smu4AmsDgIGMr56XSCSfbRMQ=,tag:/k/vUcGrBARqsUVuckV9Fw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
