apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ../kustomizeconfig.yaml

namespace: nextcloud
resources:
- manifests.yaml
- helm.yaml

secretGenerator:
- name: nextcloud-helm-secrets
  files:
  - values.yaml=helm-secrets.yaml
