adminPassword: ENC[AES256_GCM,data:i7x2tAmf8ZBbwKepmZjZAPMOOSYnzxKZTt8TEGGHi3SUtXQS3V4jnw==,iv:y6aMvc9BuXmk5cyEbePMldHuH0WcsfQiAk898e2pXfM=,tag:aap4jNdUh23Ti/U/KxRsSg==,type:str]
grafana.ini:
    auth.generic_oauth:
        client_secret: ENC[AES256_GCM,data:NBvsTBx1htM8eZ3RhKlJAcwpbBmS/fNGly2vct1AJ+kGSJwxM+jV2w==,iv:/g0bb8boExy0uPON1qUP7RkJbTQRhkku07ihwm6yXB0=,tag:44jREAcxtIn6oLl8wz2BYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cw2ap3s3ufwreunvql5xpk56hf77hdkp4y586fcghpxeq27nw9zq0mse9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub1YxQ1dsZ3NoMTNnUmk1
            UmFlWnc2VEg1RUNzYThpeUlLVFZyN2QvdDBNClpFejdiTnBRVkI1YzZYUnYwR0ox
            RDVKQm5BSXU2M0REU05FVUExUWFOdmcKLS0tIGh3RFBjVmdwaU05Z1FYUnVBVjVI
            MVdPZkQ3OVE4cURKSytFQkQvR09DMTQKUwJ2J3ghmFjccnvovDJbUuWeRsto8Ae+
            9e6OyUn5X/5lt5aTAeypKKL8KiKkopy9akBQkViVtKCOfohPM1YM/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T22:19:55Z"
    mac: ENC[AES256_GCM,data:JsWSmCCwk40F0YGdT29lc62vVSjDZ0w+lRRmBD7VxkMax3HN6sWViaSP9F67brLRcBm4KtP+F13UgBzovD/ZcDHpwEX2Q+z3JXF2f749y5MKUcUkXU+cLspCZvoIjokxIYeUQrf3YVV54EVwzq2hJWrqtyf8iHIauJBl4QUs+qU=,iv:A92PsU+P16p0vmDz1QDCLWSbm5ZvWgHpoZle1mkuU1k=,tag:qK9iFEIHkbGI9M/ft6C+ug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
