apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  secretName: grafana-cert
  dnsNames:
  - grafana.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
