apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ./kustomizeconfig.yaml

namespace: flux-system
resources:
- ./flux-components-minus-crds.yaml
- ./repo-homes.yaml

secretGenerator:
- name: flux-webhook
  files:
  - token=./repo-homes-webhook-secret
