apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      version: "~4.9.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

    controller:
      kind: DaemonSet

      config:
        allow-snippet-annotations: "true"

      tolerations:
      - key: dedicated
        operator: Equal
        value: gateway
        effect: NoSchedule

      # nodeSelector:
      #   topology.kubernetes.io/zone: gateway

      service:
        enabled: false

      hostPort:
        enabled: true

      networkPolicy:
        enabled: true

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

        # prometheusRule:
        #   enabled: true
        #   # rules: []

      opentelemetry:
        enabled: false

    ## Default 404 backend
    ##
    defaultBackend:
      enabled: false
