apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx
resources:
- manifests.yaml
- helm.yaml

# FIXME in service-monitor:
  # namespaceSelector:
  #   matchNames:
  #     - default
