---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    # FIXME find out about hostport exemption
    # https://kubernetes.io/docs/concepts/security/pod-security-admission/#exemptions
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
