apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1h0m
  releaseName: velero
  chart:
    spec:
      chart: velero
      # https://artifacthub.io/packages/helm/vmware-tanzu/velero
      version: "~5.3.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    # for defaults see https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

    initContainers:
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.7.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins

    configuration:
      features: EnableCSI
      # default: 1m
      backupSyncPeriod: 10m0s

      backupStorageLocation:
      - provider: aws
        bucket: velero-bonpland
        config:
          s3Url: https://s3.eu-central-003.backblazeb2.com
          region: eu-central
          s3ForcePathStyle: true

      volumeSnapshotLocation:
      - provider: aws


    credentials:
      existingSecret: backblaze-velero-bonpland-bucket

    deployNodeAgent: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      # priorityClassName: ""
      tolerations:
      - key: dedicated
        operator: Equal
        value: gateway
        effect: NoSchedule

      resources:
        requests:
          cpu: 0.2
          memory: 0.5Gi

    metrics:
      enabled: true
      scrapeInterval: null
      scrapeTimeout: null

      podAnnotations: null

      serviceMonitor:
        enabled: true
        autodetect: true

      nodeAgentPodMonitor:
        autodetect: true
        enabled: true

      prometheusRule:
        autodetect: true
        enabled: false

    upgradeCRDs: false
    cleanUpCRDs: false
