apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1h0m
  releaseName: velero
  chart:
    spec:
      chart: velero
      # https://artifacthub.io/packages/helm/vmware-tanzu/velero
      version: "~5.3.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    # for defaults see https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

    configuration:
      # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
      # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
      backupStorageLocation:
        # name is the name of the backup storage location where backups should be stored. If a name is not provided,
        # a backup storage location will be created with the name "default". Optional.
      - provider: aws
        bucket: velero-bonpland

    deployNodeAgent: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      # Pod priority class name to use for the node-agent daemonset. Optional.
      priorityClassName: ""
      # Resource requests/limits to specify for the node-agent daemonset deployment. Optional.
      # https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
      resources:
        requests:
          cpu: 0.2
          memory: 0.5Gi

    metrics:
      enabled: true
      scrapeInterval: null
      scrapeTimeout: null

      podAnnotations: null

      serviceMonitor:
        enabled: true
        autodetect: true

      nodeAgentPodMonitor:
        autodetect: true
        enabled: true

      prometheusRule:
        autodetect: true
        enabled: false

    upgradeCRDs: false
    cleanUpCRDs: false
