apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero
resources:
- manifests.yaml
- helm.yaml

secretGenerator:
- name: backblaze-velero-bonpland-bucket
  files:
  - cloud=./backblaze-velero-bonpland-bucket-secret
- name: velero-repo-credentials
  files:
  - repository-password=./kopia-repo-secret
  options:
    disableNameSuffixHash: true
