---
apiVersion: v1
kind: Namespace
metadata:
  name: set-in-kustomization

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
spec:
  interval: 1h0m
  url: https://vmware-tanzu.github.io/helm-charts/

# ---
# apiVersion: velero.io/v1
# kind: BackupStorageLocation
# metadata:
#   name: backblaze
# spec:
#   # https://github.com/vmware-tanzu/velero-plugin-for-aws#setup
#   provider: aws
#   default: true
#   objectStorage:
#     bucket: velero-bonpland
#   credential:
#     name: backblaze-velero-bonpland-bucket
#     key: aws-credentials

#   # "endpoint": "s3.eu-central-003.backblazeb2.com"
#   # config:
#   #   region: us-west-2
#   #   profile: "default"
#     # --backup-location-config region=$REGION \
#     # --snapshot-location-config region=$REGION \


# # https://www.backblaze.com/docs/cloud-storage-use-the-aws-cli-with-backblaze-b2
# # > Leave the Default region name and Default output format fields blank.

# # kubectl create secret generic -n velero bsl-credentials \
# #   --from-file=aws=</path/to/credentialsfile>

# # velero backup-location create default \
# #   --provider aws \
# #   --bucket BUCKET \
# #   --credential=bsl-credentials=aws \
# #   --default \
# #   --output yaml

# # > To use this new Backup Storage Location when performing a backup, use the flag --storage-location <bsl-name> when running velero backup create.
