---
apiVersion: v1
kind: Namespace
metadata:
  name: set-in-kustomization
  labels:
    # FIXME Error creating: pods "node-agent-g6rc6" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volume "host-pods")
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vmware-tanzu
spec:
  interval: 1h0m
  url: https://vmware-tanzu.github.io/helm-charts/
