apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1h
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      version: "~1.13.3"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    # default values: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
