apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm.yaml

configMapGenerator:
- name: grafana-agent
  files:
  - config.river
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: grafana-agent-config-secrets
  files:
  - mimir-password
  - loki-password
  options:
    disableNameSuffixHash: true
