apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ../kustomizeconfig.yaml

namespace: monitoring
resources:
- ./manifests.yaml
- ./grafana/
- ./mimir
# - ./loki
# - ./grafana-agent
# - ./kube-prometheus-stack
