apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mimir
spec:
  secretName: mimir-cert
  dnsNames:
  - mimir.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
