---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nextcloud-aio
spec:
  interval: 1h
  url: https://nextcloud.github.io/all-in-one/

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud
spec:
  secretName: nextcloud-cert
  dnsNames:
  - nextcloud.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
