nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    path: spec/valuesFrom/name    
- kind: Secret
  version: v1
  fieldSpecs:
  - kind: HelmRelease
    path: spec/valuesFrom/name
