apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ./kustomizeconfig.yaml

namespace: erpnext
resources:
- ./manifests.yaml

configMapGenerator:
- name: helm-values
  files:
  - values.yaml=./helm-values.yaml

secretGenerator:
- name: helm-values
  files:
  - values.yaml=./helm-secrets.yaml
