---
apiVersion: v1
kind: Namespace
metadata:
  name: set-in-kustomization
  # labels:
  #   pod-security.kubernetes.io/enforce: privileged
  #   pod-security.kubernetes.io/enforce-version: latest

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: frappe
spec:
  interval: 1h0m
  url: https://helm.erpnext.com

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: erpnext
spec:
  interval: 1h0m
  # releaseName: erpnext
  chart:
    spec:
      chart: erpnext
      # for available version see https://artifacthub.io/packages/helm/erpnext/erpnext
      version: ~7.0.38
      sourceRef:
        kind: HelmRepository
        name: frappe
  install:
    crds: Skip
  upgrade:
    crds: Skip
  valuesFrom:
  - kind: ConfigMap
    name: helm-values
  - kind: Secret
    name: helm-secrets

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: erpnext
spec:
  secretName: erpnext-cert
  dnsNames:
  - erpnext.webwur.st
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
