apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage
resources:
- manifests.yaml
- helm.yaml

images:
- name: docker.io/rancher/local-path-provisioner
  newTag: v0.0.26
  digest: sha256:aee53cadc62bd023911e7f077877d047c5b3c269f9bba25724d558654f43cea0
