oidcSecret:
    clientSecret: ENC[AES256_GCM,data:1DT/9PBzWCZCilIfQmHMAi4aNexlQsniln+Q3TocKLO2Bo+JBVovlg==,iv:d6HsJ/XbW8WcSqEvXYq2F9FSqeRLUFUy/9pqxT61T0g=,tag:Yh+AgI96yqztfliTNa2uMQ==,type:str]
    adminUser:
        #ENC[AES256_GCM,data:TEPDO3KW+3NZu8aVLtAs3RgS7anVjnpaUqcoQpkKReb7zpESqm4DV9okkhEHgKic0VUM,iv:09Sf/fSnuXO7EIhJ1/ADD3PntkI0oYAp3tSy2m1CZY8=,tag:4+6ZNv3XYyhisKamiPLihg==,type:comment]
        #ENC[AES256_GCM,data:AQalwzBcwkF0eS4dqv65iKi03G2W+RuEZFRae3RWV+1UFUW/VkGP1ME3Esq5M1Ba2/8UW9kIACEi8CW391JkpZYI/LK0fJNBlpoUX9W41+ITEJpJ5KipRvHcup8o6JKhqbF5fvEAHig7nC3U,iv:dj/dTVRyCMquJTQ+a4NoJufqAsJlrJXTjfqWYdMevqQ=,tag:K/eGhnzR4VK0k15I1Iw/iA==,type:comment]
        #ENC[AES256_GCM,data:F+MlaKdue/ssNnwwmcsbKW1Ezbp4CJJkWt6Xojb7YOKEsuIexahv8/s8BYDubHuXWlROmym6xEwymLGnMBMZVjTBarpD,iv:JLLJjrFwzhxoe5UA6A+/tS4mB19riVsHVsVH1oRaLyk=,tag:q2FB8py5c3xx+i2C/6bdHQ==,type:comment]
        #ENC[AES256_GCM,data:jgp9DW5xaUNifyru6YMePKX0PuzSG/G4Fgaqkn4/BzfYL9npyGSPhTFH2GKGkFqnsf7B8GW60G6ADnMVt/VxksTBH9oY6iNSKeFeQx+aXht0Bnmj6NZgyQ==,iv:EmdoA7QPjTRFNnwoU3JxjWVaEhsipQ2y+cAyBw0POvQ=,tag:Mut++NNLptTVSFnXo991Zg==,type:comment]
        #ENC[AES256_GCM,data:4HaOADM6NFeZlrqZsN+KSPjjGzsEZonX2Q==,iv:vWtt0cs50EsV7SH/xunnhpEHhoWkburLP5sIiVDuoIs=,tag:nf7AzoWQUki00SWt1IEXlA==,type:comment]
        passwordHash: ENC[AES256_GCM,data:AvP1NFEKqxc7++22WWQAq34D3XbUX/8G1ygONyYy4lHjlbhS2+g1c6WLPMcJQBX4bffE3lzVu0+CeOeE,iv:1uCsSlC7RgS5sWhuBn4j8kPyGZza9giNPoNjrZLT2H0=,tag:dab+4LCQVnBEXy13dYolFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cw2ap3s3ufwreunvql5xpk56hf77hdkp4y586fcghpxeq27nw9zq0mse9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZHNoUDE4bko2NmxRTE5T
            R0E5QWZnT3lTM0VrYzg5NGxPcUJBOVMxQ1RJClczZWw3bUd3dEVZV1JIemd2dEJO
            YVFrdTRQQ3Fyb2w1bGVPWEVJbDQ1QWcKLS0tIDdqZnB3bUVYb2tVbDJ6M3ZTYS9l
            ZXNDbFNqSWVUQTljQWlxVm91V3RsUEkKipz0bM5eK9BvDyLYYlrg+d89uCP3VAag
            vsGqOZ29Jh0wgq0RM98Qh+j0idRqx6mIXWlM7fdrpbh9qr1rgtdcaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T12:48:49Z"
    mac: ENC[AES256_GCM,data:wemLBe1bvuKdi1LBv+OuM18ci0JX8oUBcQj7XZVyEn/HG85IxFkmm+wc4/W3fpt2NimIKfQfazhRH0EMaaJlIdQaei4haWI5Etmc5Qe2DLWyDN1RhVA86MoYZamPJ5mLv97BC7r2uYAxj0lR8Ahw+sVkh8/vezSjWkZ4Eis0980=,iv:O4Mvtbyg1CY3tRZVBWEt/Bvy6kTvnJw64voJlgzRlls=,tag:4U7MSBu/J6PM4YIcwA6FuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
