oidcSecret:
    clientSecret: ENC[AES256_GCM,data:JWWUQp/jv/C4109EW2wClkJe7Q/clFIuJG68QFMXs5VQ1/fakh6fpw==,iv:xI+0y4f3Tf9bE3ki7WPz2glbd2s5BIMm6Gr1t4PR6sA=,tag:ZEPtdX20k4R9RNS5smTxJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cw2ap3s3ufwreunvql5xpk56hf77hdkp4y586fcghpxeq27nw9zq0mse9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYW81L1dJbmpLMnJRcE9J
            NXR3dSt0M1lYYVl5ZmtLVFFra21qWHJ1K2pnCjVCaTQ0TDNiNm44TEhqUG5wTHhL
            RlhXN2ZGNVJlWEtCQk5LSENVSGxsMDgKLS0tIDY2ZUpDdE1BeUxidTJRV1p0KytD
            VVpWU2tsMlZlNGZDQnlmWmZ6VVg2ejAK5XDOa/+Q6Cpw9KXF/6zERkLwTaIx0DVU
            vy+8kJKmajw+zwBC14bcV+MMz8FBvPn/YyRFwlilRzXaIY5d7zV5DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T22:12:17Z"
    mac: ENC[AES256_GCM,data:bus0YEZQoXYkC4gq92WBfgcs7qdK5eqWxA55LEi85k6rF5TfKra9NEu2/9AOG5LA4K/V8L7no2mXHnr4hIwfZeTN2tdw7xm88cynjQHtkZJ8/4elxeHV0XHvkvEXmLEQKqC+sm+GyjScwRpV+FtZnCYjXHylxjD3ny0x8sXf+O8=,iv:jzdkamGN1rvYFmZzjoaiSPQkbQeQchAVwtbyuSyr2QQ=,tag:latZwaXHU6AJh17lt2wdXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
