apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ./kustomizeconfig.yaml

resources:
- ./manifests.yaml
- ./rbac.yaml
- ./helm.yaml

secretGenerator:
- name: flux-ui-helm-secrets
  files:
  - values.yaml=./helm-secrets.yaml
