---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps
      Dashboard's helm chart.
  # labels:
  #   app.kubernetes.io/component: ui
  #   app.kubernetes.io/created-by: weave-gitops-cli
  #   app.kubernetes.io/name: weave-gitops-dashboard
  #   app.kubernetes.io/part-of: weave-gitops
  name: weaveworks
spec:
  interval: 1h0m
  type: oci
  url: oci://ghcr.io/weaveworks/charts

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flux-dashboard
spec:
  secretName: flux-dashboard-cert
  dnsNames:
  - flux.m.elmonitor.de
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer

# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: cm-acme-http-solver
# spec:
#   policyTypes:
#   - Ingress
#   ingress:
#   - ports:
#     - port: 8089
#       protocol: TCP
#   podSelector:
#     matchLabels:
#       acme.cert-manager.io/http01-solver: "true"
